### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by thanegill** [RxSwiftCommunity/RxOptional#1]

**Comment by ashfurrow** [comment]
Looks this this was done, then eh?

**Comment by thanegill** [comment]
Doing it now. You'll see why I moved it first in a second.

**Comment by thanegill** [comment]
Done now.

**Comment by thanegill** [comment]
Well they are done but travis isn't configured yet #3. I'm a little new to CI. Do you think you could help @ashfurrow?

**Comment by ashfurrow** [comment]
Sure, I can take a look!
