### ISSUE TITLE
filterNil rename to unwrapNil

### ISSUE THREAD

**Issue by mbalex99** [RxSwiftCommunity/RxOptional#17]
Shouldn't we keep filter as a plucking of items in the stream without modifying the underlying generic type?
Since the act of retrieving a type from `String?` to `String` is usually deemed as unwrapping nullables, I suggest we keep.
At least `filterAndUnwrap`.

Thoughts?

**Comment by thanegill** [comment]
If anything it should be `flatMapOptional`, as an Optional and Observable are both monads.

**Comment by ashfurrow** [comment]
¯\\_(ツ)_/¯ I'm fine with whatevs. I used `filterNil` because I needed it and was under time-pressure to ship. We can deprecate it and introduce something else.

**Comment by devandanger** [comment]
I always thought it was somewhat confusing to see .filter* operators in a stream only to find out its doing a flatMap underneath.  I've seen filterSuccessStatusCodes examples in similar scenarios.  I usually recommend a different method extension altogether so you have to dig in to what operator its based on and can't make incorrect assumptions from the call site.  I'm sure there's a competing argument though.

**Comment by freak4pc** [comment]
I personally respectfully disagree.

A method would be named based on what it does, and not based on its
underlying implementation.

As far as a developer is concerned, nils are filtered and only non-nil
stuff are passed forward which makes 100% sense for both readability, code
clarity and self-documentation of a method

This is al my personal opinion OFC :)

-- 
Shai Mishali

**Comment by devandanger** [comment]
I agree that naming methods should be tied to what it does, unless you're entering an obfuscating coding contest 😃.  But there is strong terminology of names for operators and what they do in Rx.  So when I see filter I'm expecting the same sequence type, but filtered out elements.  In some of these cases, though I come to find its really a mapping operator.

This particular case makes sense as...
```
T? -> T 
```
... is a mapping operation.

But onboarding new devs to RxSwift comes with a learning curve.  So when you do the following
```
T? -> T
```
And call it filter* ... you're overloading the filter terminology and it can be confusing.

**Comment by freak4pc** [comment]
Yup I totally understand that basic confusion, since without it, this question would probably not arise. I still feel like for a beginner (or even for more seasoned Rx developers), this method name makes sense even though it has a different return type. I would personally not be against adding an alias method called `unwrap()` but leaving the original `filterNil()` method.

**Comment by scottrhoyt** [comment]
When we created a similar operator for a project, we called it `ignoreNil`. Maybe that would work to clear up the confusion while still being having good DX.

**Comment by freak4pc** [comment]
I don't like that naming either. There's no other operator using the `ignore` naming AFAIK...

**Comment by ashfurrow** [comment]
Maybe `unwrapOptionals` would be best?
