### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ashfurrow** [RxSwiftCommunity/RxOptional#19]
Borked in #18 because of Swift updates, probably. Needs investigation.

**Comment by thanegill** [comment]
Looks to be be the same as here: https://github.com/SwiftyBeaver/SwiftyBeaver/pull/79,

xctool is [fixed](https://github.com/facebook/xctool/issues/666), just waiting for travis to update to the new version.

**Comment by ashfurrow** [comment]
Cool, sounds like you're on top of this, gonna re-assign :wink:

**Comment by ashfurrow** [comment]
Fixed in 665b1a29a3ff54dfb286eb621c126c7a701e0c3d
