### ISSUE TITLE
Carthage compatibility?

### ISSUE THREAD

**Issue by grangej** [RxSwiftCommunity/RxOptional#25]
Can we make this compatible with Carthage please?

**Comment by ashfurrow** [comment]
Sure, Carthage would be welcome. I'm not a Carthage user, but would welcome a pull request that adds support. [RxAlamofire](https://github.com/RxSwiftCommunity/RxAlamofire) supports Carthage, would be a good place to start.

**Comment by muukii** [comment]
@ashfurrow 
I'll submit Carthage support PR, when Swift3 supported.
Are you sure you want to abolish the template of CocoaPods?

**Comment by ashfurrow** [comment]
Thanks! I need to keep CocoaPods support actually.

**Comment by muukii** [comment]
@ashfurrow 
Okay.
I will try to be able to both support of CocoaPods and Carthage.
Swift3 support when completed?

**Comment by ashfurrow** [comment]
Thanks! I haven't had a chance to get to Swift 3 support, I'll probably do it sometime next week unless someone else submits a pull request before I can.

**Comment by ashfurrow** [comment]
Looks like Swift 3 is already in progress: https://github.com/RxSwiftCommunity/RxOptional/pull/27 I'll try to take a look today.

**Comment by ashfurrow** [comment]
Should be fixed by #31, once it's merged, can you check to see if it's working?

**Comment by Lutzifer** [comment]
Added Documentation for Carthage to Readme
