### ISSUE TITLE
Duplicate CI builds

### ISSUE THREAD

**Issue by ashfurrow** [RxSwiftCommunity/RxOptional#32]
Our current Travis setup has [four schemes](https://github.com/RxSwiftCommunity/RxOptional/blob/2b24a67ad2352c3bd4d7b09536da1da24ba906f6/.travis.yml#L10-L13) which kick of four distinct builds on Travis. However, `carthage bootstrap` is run on each build and it builds for all platforms, so we're doing the same work four times (I think someone please double check my logic here). Seems like we might be able to speed up CI by getting rid of building unnecessary schemes?

**Comment by ashfurrow** [comment]
I also don't see us actually running the tests, just building them. Looks like it was introduced in #28, that's my bad, should've been more thorough.

**Comment by Lutzifer** [comment]
We can remove the xcode_scheme section, replace it with

```
env:
  - PLATFORM=iOS
  - PLATFORM=tvOS
  - PLATFORM=Mac
  - PLATFORM=watchOS
```

and then call

```
carthage bootstrap --platform $PLATFORM
```

Not yet tested, but this should solve it.

**Comment by Lutzifer** [comment]
@ashfurrow We can close this then?
