### ISSUE TITLE
RxCocoa Driver changes break RxOptional extensions

### ISSUE THREAD

**Issue by neoplastic** [RxSwiftCommunity/RxOptional#33]
The Driver object is now typealiased to SharedSequence thus breaking the extensions used to call RxOptional.

**Comment by neoplastic** [comment]
I've written some changes for this, I'll post it in a bit after some testing.

**Comment by redent** [comment]
This can probably be closed as [this commit](https://github.com/RxSwiftCommunity/RxOptional/commit/93d12b3c3bfc1886ebd038149b24a8d7d6ef1ea4) fixed it
