### ISSUE TITLE
Non-nominal type 'Drive' cannot be extended

### ISSUE THREAD

**Issue by devSC** [RxSwiftCommunity/RxOptional#35]

**Comment by tranvutuan** [comment]
Im doing a migration to swift3 and having a same problem. Wondering if we have any plans on it yet ?

**Comment by sergdort** [comment]
Hi, guys `Driver` is [not a type now](https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/CocoaUnits/Driver/Driver.swift#L38) it's a generic `typeallies`

you can extend `SharedSequenceConvertibleType` for example 

```swift
extension SharedSequenceConvertibleType where E: ResultType {
    func filterError() -> SharedSequence<SharingStrategy, Error> {
        return flatMap { state -> SharedSequence<SharingStrategy, Error> in
            if let error = state.error {
                return SharedSequence.just(error)
            }
            return SharedSequence.empty()
        }
    }
}
```

**Comment by tranvutuan** [comment]
@sergdort: thanks. I'm wondering if the RxOptional will be updated to match with the latest changes for swift3 from RxCocoa and RxSwift ?

**Comment by shams-ahmed** [comment]
@tranvutuan if your able to do a PR, I'll be happy to review and merge the changes...
