### ISSUE TITLE
Depreciate fatalErrorOn* Operators

### ISSUE THREAD

**Issue by thanegill** [RxSwiftCommunity/RxOptional#4]
They don't seem to be a good idea. They: 
- Promote bad design
- For the majority of the cases falls back to some other operator.
- Can't test.

Deprecating in 1.2 and removing in 2.0.

Any reason to not remove these operators @RxSwiftCommunity/contributors?

**Comment by thanegill** [comment]
Todo:
- [ ] Add message to README
- [ ] Remove from Examples
- [ ] Remove Operators
- [ ] Release version 2.0

**Comment by ashfurrow** [comment]
Looks like they're marked as obsoleted now, as of "2.0", which means iOS 2 I think? I agree we should remove them.

**Comment by thanegill** [comment]
Yeah, forgot that was only a proposal for swift, deprecated using framework version numbers, not just OS versions. All tests pass now!  Thanks for all your help @ashfurrow!

**Comment by ashfurrow** [comment]
:bow:
