### ISSUE TITLE
Missing tag for 2.1.0 version

### ISSUE THREAD

**Issue by Festyk** [RxSwiftCommunity/RxOptional#41]
Cocapods can't find that version because it doesn't have a release tag.

**Comment by ashfurrow** [comment]
Yikes, thanks for opening an issue. I'll look into this now.

**Comment by ashfurrow** [comment]
Okay, I've used db3ca92934b3bfadde9197b4d0dcbe148cf48343 as the target for the 2.1.0 tag, since it includes the `distinctUntilChanged` operator mentioned in the changelog. Can you verify this works on your end?

**Comment by Festyk** [comment]
I tried `pod repo update` and `pod setup` but still getting error: 
Unable to satisfy the following requirements:
- `RxOptional (= 2.1.0)` required by `Podfile`

Any suggestions?

**Comment by ashfurrow** [comment]
Yeah, looks like that version wasn't pushed to CocoaPods trunk (I thought the original problem was that it had been pushed to trunk without a corresponding tag). I'll take a look 👍

**Comment by ashfurrow** [comment]
It _should_ be fixed now, sorry for all the back and forth.

**Comment by Festyk** [comment]
Sorry for delay but I checked it now and everything is working now. Thanks for the help. I really needed this distinctUntilChanged extension ;)
