### ISSUE TITLE
codebuild: error: Unable to find a destination on carthage build

### ISSUE THREAD

**Issue by Codebear98** [RxSwiftCommunity/RxOptional#44]
**cartfile**
`github "RxSwiftCommunity/RxOptional"`

**Command**
`
carthage build RxOptional --platform watchOS
`

**Error Log**
`codebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:watchOS Simulator, id:48D0931A-D041-4D51-9BEB-FA8D924CA1C0 }

	Ineligible destinations for the "RxOptional watchOS" scheme:
		{ platform:watchOS, id:dvtdevice-DVTiOSDevicePlaceholder-watchos:placeholder, name:Generic watchOS Device }
		{ platform:watchOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-watchsimulator:placeholder, name:Generic watchOS Simulator Device }
A shell task (/usr/bin/xcrun xcodebuild -project /Users/henry.hong/workspace/scmp-mobile/scmp-ios/Carthage/Checkouts/RxOptional/RxOptional.xcodeproj -scheme RxOptional watchOS -configuration Release -sdk watchsimulator -destination platform=watchOS Simulator,id=48D0931A-D041-4D51-9BEB-FA8D924CA1C0 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 70:
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:watchOS Simulator, id:48D0931A-D041-4D51-9BEB-FA8D924CA1C0 }

	Ineligible destinations for the "RxOptional watchOS" scheme:
		{ platform:watchOS, id:dvtdevice-DVTiOSDevicePlaceholder-watchos:placeholder, name:Generic watchOS Device }
		{ platform:watchOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-watchsimulator:placeholder, name:Generic watchOS Simulator Device }`

**Comment by ashfurrow** [comment]
Hmm, sorry to hear you're having this problem! I'm not that experienced with Carthage, has anyone from @RxSwiftCommunity/contributors seen something like this?

**Comment by reloni** [comment]
According to this thread (https://github.com/Carthage/Carthage/issues/950) there is incorrect TARGETED_DEVICE_FAMILY in watchOS scheme. It seems for watchOS it should be: TARGETED_DEVICE_FAMILY = 4 (now it's 1,2 - that means iPhone and iPad). I checked out this project and manually changed device family, after that carthage works fine.

**Comment by Codebear98** [comment]
Yes, found the solution, it's the project settings, the targeted_device_family in watchOS project is set to 1,2 which should be 4. 

I can build watchOS via Carthage with this setting.

https://github.com/Codebear98/RxOptional/tree/bugfix/carthage_watchos?files=1

**Comment by freak4pc** [comment]
Closed by #53
