### ISSUE TITLE
New release to fix Carthage issues with RxOptional release 3.4.0

### ISSUE THREAD

**Issue by sashei** [RxSwiftCommunity/RxOptional#57]
We are able to continue using `RxOptional` locally by applying the fix to our local version of `RxOptional`, but any `carthage update` either locally or in our CI environment will cause compilation errors. Please make a point release to keep `RxOptional` building in Carthage properly.

**Comment by freak4pc** [comment]
https://github.com/RxSwiftCommunity/RxOptional/releases/tag/3.4.1
