### ISSUE TITLE
Moving RxOptional to RxSwiftExt project

### ISSUE THREAD

**Issue by MortyMerr** [RxSwiftCommunity/RxOptional#77]
Hi @RxSwiftCommunity/contributors! I have a proposal to merge RxOptional into RxSwiftExt.
Both these project follow similar great target - make RxSwift users life easier with custom handy operators. I think it might be a good idea to have one repo with all custom operators, not two or more. It will also make maintaining, updates and resolving issues easier. And, of course, it will increase users number, cause some folks once found RxOptional and don’t know about RxSwiftExt or visa versa. 

What do you think? Please, share your thoughts. In case you like this idea, I am ready to handle migration process.

P.S. Got approval on that from @thanegill. Interested in community thoughts.
P.P.S. We all have to stay united in the face of Apple Combine
cc @freak4pc

**Comment by freak4pc** [comment]
Hey - I'm for one am somewhat against merging frameworks together. RxSwiftExt already has the potential to become too large.

RxOptional was initially built to allow easy unwrapping (with `unwrap`), RxSwiftExt already has an operator that does this, and now both of these are deprecated thanks to `compactMap`. I'm wondering what value if any RxOptional brings into RxSwiftExt at this stage?

**Comment by MortyMerr** [comment]
Too large for what? I thought that’s just a repo with custom RxSwift operators, which makes life easier but could not be placed to main repo for some reasons. If someone doesn’t want to fetch whole repo, he can just copy paste necessary functions. 

So does RxOptional, with only difference - its operators built around optional handling. But i think it’s not a reason to store them in separate project.

This repo have other operators, not only `unwrap`. They all make sense for me and for people who gave stars to this repo. So, merging these two repos will increase RxSwiftExt popularity and give more handy operators to its users. 

I don’t think that in 2019 someone is really scared of two more kilobytes in dependency size. 

What do you think? 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by freak4pc** [comment]
> This repo have other operators, not only unwrap. They all make sense for me and for people who gave stars to this repo. So, merging these two repos will increase RxSwiftExt popularity and give more handy operators to its users.

It really wouldn't - no one thinks "oh, it has stuff from RxOptional, so this is more popular now". 

We shouldn't make such broad decision. 

If you want, make a list of all of the operators in RxOptional and we can decide as a community which of them makes sense in the context of RxSwiftExt. 

The road is slippery, its not about kilobytes, it's about ABI, method signatures and symbols, build time, etc. There is no reason to overload RxSwiftExt with _everything_ IMO ... Think about it, every project in RxSwiftCommunity is an _Extension_ to RxSwift, does that mean they all should be part of RxSwiftExt?

**Comment by freak4pc** [comment]
One more thing: 

>  If someone doesn’t want to fetch whole repo, he can just copy paste necessary functions.

I don't think that's the main way people consume this project. Yes, it happens (which is why we attempt to keep operators atomic), but it quite definitely isn't the main way of consumption here.
