### ISSUE TITLE
Carthage update broken after 4.1.0

### ISSUE THREAD

**Issue by sbarow** [RxSwiftCommunity/RxOptional#84]
When running `carthage update` the following error is received 

> A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/RxSwiftCommunity/RxOptional.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/cameronmcgorian/Library/Caches/org.carthage.CarthageKit/dependencies/RxOptional)) failed with exit code 1

Seems like this occurred after the `4.1.0` release?

**Comment by freak4pc** [comment]
@fassko Since this happened under your PR, can you take a look if you have a moment?

**Comment by freak4pc** [comment]
@sbarow looks totally fine on my side: 

![image](https://user-images.githubusercontent.com/605076/67270715-e0ddab80-f4c1-11e9-9143-a6cc0b912c29.png)

**Comment by sbarow** [comment]
> @sbarow looks totally fine on my side:
> 
> ![image](https://user-images.githubusercontent.com/605076/67270715-e0ddab80-f4c1-11e9-9143-a6cc0b912c29.png)

Can you try with carthage 0.34.0?

**Comment by freak4pc** [comment]
Looks fine as well. 
Can you try `rm -rf ~/Library/Caches/org.carthage.CarthageKit` in a terminal to clear your cache and do a new `carthage update` ?

**Comment by sbarow** [comment]
> Looks fine as well.
> Can you try `rm -rf ~/Library/Caches/org.carthage.CarthageKit` in a terminal to clear your cache and do a new `carthage update` ?

That did the trick, thank you.
