### ISSUE TITLE
Support of RxSwift 6

### ISSUE THREAD

**Issue by Narayane** [RxSwiftCommunity/RxOptional#89]
Hi,

is it planned to be compliant with RxSwift 6 quickly?

Thanks.

**Comment by ashfurrow** [comment]
While _I_ have no plans to update the repo (because I don't use it day-to-day anymore) I would welcome a pull request.

**Comment by Econa77** [comment]
Looks like support is complete with RxOptional v5.0.0 👁️ 
https://github.com/RxSwiftCommunity/RxOptional/blob/45224688cb22d44fb4b830fb3ff1bc30125acbc6/RxOptional.podspec#L27-L28

**Comment by freak4pc** [comment]
Yup, sorry for not taking care of this one @jegnux is maintaining this project and released a RxSwift 6 compatible build :)

**Comment by jegnux** [comment]
Yep sorry folks. I merged the PR, I just need to configure a last thing in GitHub Actions and I'll push the release on CocoaPods. In the meantime you can directly target the main branch of this git repo to update the pod.
