### ISSUE TITLE
Error building from Carthage "xcodebuild: error: Unable to read project 'RxOptional-SPM.xcodeproj' from folder"

### ISSUE THREAD

**Issue by landonr** [RxSwiftCommunity/RxOptional#91]
When building RxOptional 5.0.0 using Carthage with Xcode 12.3 I get this error

A shell task (/usr/bin/xcrun xcodebuild -project /Users/landon/dev/app/Carthage/Checkouts/RxOptional/RxOptional-SPM.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Unable to read project 'RxOptional-SPM.xcodeproj' from folder '/Users/landon/dev/app/Carthage/Checkouts/RxOptional'.
	Reason: Project /Users/landon/dev/app/Carthage/Checkouts/RxOptional/RxOptional-SPM.xcodeproj cannot be opened because it is missing its project.pbxproj file.

**Comment by freak4pc** [comment]
Carthage doesn't seem to work well on Xcode 12. Did you check their repo? Plenty of issues about this their

**Comment by landonr** [comment]
Using [this workaround](https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323) I can build RxSwift 6.0.0 with Xcode 12.3 so I should be able to build RxOptional

If I delete RxOptional-SPM.xcodeproj before Carthage gets a chance to build RxOptional it will succeed. Why is Carthage trying to build RxOptional-SPM.xcodeproj

**Comment by freak4pc** [comment]
I don't know, but again that seems like a question for Carhtage, and not this project

**Comment by landonr** [comment]
Carthage is going to look through every .xcodeproj in the repo for shared schemes to build. RxOptional-SPM.xcodeproj doesn't contain a project.pbxproj so Carthage fails when it opens that .xcodeproj

@rynecheow is it possible to include a proejct.pbxproj inside the RxOptional-SPM.xcodeproj?

**Comment by rynecheow** [comment]
@landonr Let me check and remove shared scheme for that project - it should only be generated on CI only
